[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
jetbrainsKotlinJvm = "2.3.0"

# Our dependency versions below
androidXHilt = "1.3.0"
coroutinesCoreJvm = "1.10.2"
hilt = "2.58"
ksp = "2.3.4"
lifecycle = "2.10.0"
okHttp3 = "5.3.2"

# gRPC and ConnectRPC
connectRpc = "0.7.4"
fjarmConnectSdk = "0.7.4.1.20250220235546.9eca9e174ab9"
fjarmProtobufLiteSdk = "31.1.0.1.20250220235546.9eca9e174ab9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Our dependencies below
# Lifecycle related deps
coroutinesCoreJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutinesCoreJvm" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# ConnectRPC related deps
connectKotlin = { group = "com.connectrpc", name = "connect-kotlin", version.ref = "connectRpc" }
connectKotlinGoogleJavaLiteExt = { group = "com.connectrpc", name = "connect-kotlin-google-javalite-ext", version.ref = "connectRpc" }
connectKotlinOkHttp = { group = "com.connectrpc", name = "connect-kotlin-okhttp", version.ref = "connectRpc" }
fjarmProtobufLiteSdk = { group = "build.buf.gen", name = "fjarm_fjarm_protocolbuffers_java_lite", version.ref = "fjarmProtobufLiteSdk" }
fjarmConnectSdk = { group = "build.buf.gen", name = "fjarm_fjarm_connectrpc_kotlin_lite", version.ref = "fjarmConnectSdk" }
okHttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3" }

# Dagger and Hilt related deps
com-google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
com-google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
com-google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
com-google-dagger-hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }

androidx-hilt-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidXHilt" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# Dagger and Hilt related deps
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
