[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
jetbrainsKotlinJvm = "2.3.0"

# Our dependency versions below
coroutinesCoreJvm = "1.10.2"
okHttp3 = "4.12.0"

# gRPC and ConnectRPC
connectRpc = "0.7.4"
fjarmConnectSdk = "0.7.4.1.20250220235546.9eca9e174ab9"
fjarmGrpcSdk = "1.4.3.1.20250220235546.9eca9e174ab9"
grpcAndroid = "1.73.0"
grpcOkHttp = "1.73.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Our dependencies below
coroutinesCoreJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutinesCoreJvm" }
okHttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3" }
connectKotlin = { group = "com.connectrpc", name = "connect-kotlin", version.ref = "connectRpc" }
connectKotlinGoogleJavaLiteExt = { group = "com.connectrpc", name = "connect-kotlin-google-javalite-ext", version.ref = "connectRpc" }
connectKotlinOkHttp = { group = "com.connectrpc", name = "connect-kotlin-okhttp", version.ref = "connectRpc" }
fjarmConnectSdk = { group = "build.buf.gen", name = "fjarm_fjarm_connectrpc_kotlin_lite", version.ref = "fjarmConnectSdk" }
fjarmGrpcSdk = { group = "build.buf.gen", name = "fjarm_fjarm_grpc_kotlin_lite", version.ref = "fjarmGrpcSdk" }
grpcAndroid = { group = "io.grpc", name = "grpc-android", version.ref = "grpcAndroid" }
grpcOkHttp = { group = "io.grpc", name = "grpc-okhttp", version.ref = "grpcOkHttp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
